[build]
command = " npm run build"
publish="/build"
base="/"

[[redirects]]
 from = "/*"
  to = "index.html"
  status = 200


[[redirects]]
 from = "/html/portfoliolist.html"
  to = "/html/portfoliolist.html"
  status = 200
  force = true
  
[[redirects]]
 from = "/html/portfoliomore.html"
  to = "/html/portfoliomore.html"
  status = 200
  force = true

[[redirects]]
 from = "/html/aboutme.html"
  to = "/html/aboutme.html"
  status = 200
  force = true

  [[redirects]]
 from ="/html/myeffert.html"
  to = "/html/myeffert.html"
  status = 200
  force = true

    [[redirects]]
 from = "/html/contact.html"
  to = "/html/contact.html"
  status = 200
  force = true