

[[redirects]]
 from = "/*"
  to = "index.html"
  status = 200


[[redirects]]
 from = "/portfoliolist.html"
  to = "/portfoliolist.html"
  status = 200
  force = true
  
[[redirects]]
 from = "/html/portfoliomore.html"
  to = "/portfoliomore.html"
  status = 200
  force = true

[[redirects]]
 from = "/html/aboutme.html"
  to = "/aboutme.html"
  status = 200
  force = true

  [[redirects]]
 from ="/html/myeffert.html"
  to = "/myeffert.html"
  status = 200
  force = true

    [[redirects]]
 from = "/html/contact.html"
  to = "/contact.html"
  status = 200
  force = true